### ISSUE TITLE
在吗？能不能给我讲讲里面的逻辑，谢谢你了

### ISSUE THREAD

**Issue by MasterBetter** [bqlin/BqSubtitle#1]

**Comment by MasterBetter** [comment]
解析srt 的类

**Comment by bqlin** [comment]
具体是哪里不清晰呢

**Comment by MasterBetter** [comment]
如果中英文混合字幕，我怎么把英文和中文分离开。

**Comment by bqlin** [comment]
呃，说实话我也没有把中英文字幕分离，我只是把时间之间的字幕内容单纯地居中显示而已。如果你要分离，可以在获取得到的每一项字幕内容，然后通过换行符+检测每行字符有多少是英文字符来区分并分离中英文字幕。

**Comment by MasterBetter** [comment]
我现在已经区分了 我吧代码粘贴上

**Comment by MasterBetter** [comment]
[import.docx](https://github.com/bqlin/PLVSubtitle/files/2338684/import.docx)
